// global variable holding user name used across adventure
let userName = '';

// general greeting - step 1
const userNameGreeting = () => {
    // get users name
    userName = prompt(`Hello Brave Traveller. What's your name?`).trim();
    // if user does not give you their name, generate a random one
    if (!userName) {
        randomNameGenerator();
    }

    crossRoadsPrimary();
}

// generates random name if user does not provide one
const randomNameGenerator = () => {
    const names = [
        'Pillow MoonFace',
        'Jack WhatsTheirFace',
        'Cat McCatFace',
        'Hotdog'
    ]

    // random number for name array
    const randomNumberForName = Math.floor(Math.random() * names.length);

    const fakeUserName = names[randomNumberForName];

    userName = prompt(`I'm afraid we don't let strangers in the enchanted woods without knowing their names. If you don't give us a name, we'll be forced to call you ${fakeUserName}.`);

    if (!userName) {
        userName = fakeUserName;
    }

}

// warning and first choice for direction: choices LEFT or RIGHT - step 2
// choices: ghost question and spelling backwards
const crossRoadsPrimary = () => {
    const rightOrLeft = prompt(`Well, well...few want to enter the magic forest, ${userName}. Let's get started. Do you want to go right or left?`).trim();

    let rightToLeftFixes = rightOrLeft.toLowerCase();

    if (!rightToLeftFixes) {
        alert(`${userName}, you can't just stay here! You'll just have to go the right.`);
        toTheRight();
    } else if (rightToLeftFixes === 'right') {
        toTheRight();
    } else if (rightToLeftFixes === 'left') {
        toTheLeft();
    } else {
        alert(`${userName}, you can't just stay here! You'll just have to go the right.`);
        toTheRight();
    }
};

// spooky alerts
const spookyHouseAlert = () => {
    alert('There\'s a spooky house up ahead. Let\'s go inside!');
};

const desertedCottageAlert = () => {
    alert('You see a deserted cottage up ahead. Let\'s check out what\'s inside - what can go wrong?');
}

// game directions
// ghost random number guessing game - step 3
const ghostNumberGuessing = () => {
    spookyHouseAlert();

    // random number generated by ghost
    const ghostNumberGuest = Math.floor(Math.random() * 3);

    let userNumberGuess = prompt(`Boo! The friendly neighbourhood ghost came out to play! He loves playing games. If you can guess what number he's thinking of between 0 and 3, he'll let you pass!`);

    if (!userNumberGuess || userNumberGuess != ghostNumberGuest) {
        userNumberGuess = prompt('Oh no, try again!');

        if (!userNumberGuess || userNumberGuess != ghostNumberGuest) {
            userNumberGuess = prompt(`So close! Try again, ${userName}!`);

            if (!userNumberGuess || userNumberGuess != ghostNumberGuest) {
                alert(`You're lucky the ghost is friendly, ${userName} - he's going to let you through even though you didn't quite guess the right number.`);
            } else {
                alert('You got it! Keep going down the path...if you dare!');
            }
        } else {
            alert('You got it! Keep going down the path...if you dare!');
        }
    } else {
        alert(`You got it, ${userName}! Keep going down the path...if you dare!`);
    }
};

// witch backwards spelling game - step 3
const backwardsSpelling = () => {
    desertedCottageAlert();

    const userSpellingBackwards = prompt(`A spooky witch pops out and asks you to type 'Cats like to party' backwards. You only have one shot!`).trim();

    // original answer string
    const ogString = 'cats like to party'.split('').reverse().join('');

    // lower casing user response
    const cleanedUpUserSpellingBackwards = userSpellingBackwards.toLowerCase();

    if (!userSpellingBackwards || cleanedUpUserSpellingBackwards != ogString) {
        alert(`Oh no! You got it wrong, ${userName}! You're lucky the witch is feeling generous and is going to let you go free!`);
    } else if (cleanedUpUserSpellingBackwards === ogString) {
        alert(`You did it, ${userName}! You get to go free from the witch's cottage!`);
    } else {
        alert(`Oh no! You got it wrong, ${userName}! You're lucky the witch is feeling generous and is going to let you go free!`);
    }

};

// general goodbye - step 4
const finalGoobye = () => {
    alert(`${userName}, you survived the magic forest! Hooray!`);
};

// to the right (ghost random number guess first) - complete right journey
const toTheRight = () => {
    ghostNumberGuessing();
    backwardsSpelling();
    finalGoobye();
};

//to the left (spelling backwards first) - complete left journey
const toTheLeft = () => {
    backwardsSpelling();
    ghostNumberGuessing();
    finalGoobye();
}


$(function() {
    userNameGreeting();
});